import type { CalendarProposal, ConversationTurn, EmailDraft, FollowUpItem, Notification } from "../../lib/api";
import type { SeverityPalette } from "../../lib/severity";

export type NotificationPanelProps = {
  notification: Notification;
  linkedTurns: ConversationTurn[];
  palette: SeverityPalette;
  liveTranscript: string;
  audioControls: React.ReactNode;
  mailboxConnected: boolean;
  onOpenSettings: () => void;
  followUpDetails: FollowUpItem | null;
  activeDraft: EmailDraft | null;
  draftRecipient: string;
  draftSubject: string;
  draftBody: string;
  draftSyncHint: string | null;
  draftActionError: string | null;
  isDraftSaving: boolean;
  onDraftRecipientChange: (value: string) => void;
  onDraftSubjectChange: (value: string) => void;
  onDraftBodyChange: (value: string) => void;
  onDraftUseSuggestion: (email: string) => void;
  onDraftSave: () => void;
  onDraftSend: () => void;
  onDraftCancel: () => void;
  activeCalendarProposal: CalendarProposal | null;
  calendarError: string | null;
  isCalendarPlanning: boolean;
  isCalendarSaving: boolean;
  proposalTitle: string;
  proposalStartAtInput: string;
  proposalEndAtInput: string;
  proposalAttendeesInput: string;
  proposalNotes: string;
  onProposalTitleChange: (value: string) => void;
  onProposalStartAtChange: (value: string) => void;
  onProposalEndAtChange: (value: string) => void;
  onProposalAttendeesChange: (value: string) => void;
  onProposalNotesChange: (value: string) => void;
  onCalendarApprove: () => void;
  onCalendarCancel: () => void;
  isFeedbackProcessing: boolean;
  onOpenHistory: () => void;
  onDismiss: () => void;
  isDismissingNotification: boolean;
};
